server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      database: xc_cms
      host: 47.107.128.204
      port: 27017
  rabbitmq:
    host: 47.107.128.204
    port: 5672
    username: xcEdu
    password: 123456
    virtualHost: /
xuecheng:
  mq:
    # cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01
    # 此routingKey为门户站点ID
    routingKey: 5a751fab6abb5044e0d19ea1
