server:
  port: 31001
spring:
  rabbitmq:
    host: 192.168.136.110
    port: 5672
    username: xcEdu
    password: 123456
    virtualHost: /
  freemarker:
    # 关闭缓存
    cache: false
    settings:
      # 模板更新时间，正式环境可以设置较大
      template_update_delay: 0
  application:
    name: xc‐service‐manage‐cms
  data:
    mongodb:
      host: 192.168.136.110
      port: 27017
      database: xc_cms
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/,http://localhost:50102/eureka/}
  instance:
    prefer‐ip‐address: true  #将自己的ip地址注册到Eureka服务中
    ip‐address: ${IP_ADDRESS:127.0.0.1}
    instance‐id: ${spring.application.name}:${server.port} #指定实例id